#docker network create omuzgor_network
 FROM farruq1988/php8.2:myapp
#
# FROM farruq1988/php8.2-fpm:macm1
#
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer




